- name: copy file with vars
  template:
    src: "{{ object['file_name_src'] }}"
    dest:  "{{ object['file_name_dest'] }}"

- name: execute python file
  shell:
    cmd: python3 {{ object["file_name_dest"] }}
  ##register permet de stocker le retour d'un module dans une variable
  register: result_shell