
---

- hosts: all
  become: true
  tasks:
  - include: include_tasks.yml object={{item}}
    with_items:
    - file_name_src: file_1.py.j2
      file_name_dest: ./file_1.py
    - file_name_src: file_2.py.j2
      file_name_dest: ./file_2.py 
  
  - name: debug python file return
    debug:
      var: result_shell.results[{{ item }}].stdout_lines
    with_items:
      - 0
      - 1
      - 2
    

